### ISSUE TITLE
Obtaining nth item on str works but not on list

### ISSUE THREAD

**Issue by arvindpdmn** [pytoolz/toolz#330] opened 2016-09-25 10:39 UTC
I tried the following. Not sure what I am doing wrong. Looks like integer argument is being treated as the sequence. Version of toolz is 0.8.0 on Windows 10.

```
>>> from toolz import itertoolz                                                                                                   
>>> data = [1, 2, 8, 5, 5, 2, 9]                                                                                                  
>>> list(itertoolz.nth(3, data))                                                                                                  
Traceback (most recent call last):                                                                                                
  File "<stdin>", line 1, in <module>                                                                                             
TypeError: 'int' object is not iterable                                                                                           
>>>
```

**Comment by mrucci** [comment] 2016-09-27 19:20
The problem is that you are feeding an integer to the list constructor

    list(itertoolz.nth(3, data)) == list(5)

The list constructor instead accepts an iterator: https://docs.python.org/2/library/functions.html#list

**Comment by eriknw** [comment] 2016-10-05 14:21
@mrucci is correct, `itertoolz.nth(3, data)` returns `5` (the value at the index of 3).  Calling `list(5)` raises the exception, so don't call `list`.

Thanks for raising an issue, @arvindpdmn.  Please don't be shy in the future!

Closing.

**Closed by eriknw** 2016-10-05 14:21 UTC
