### ISSUE TITLE
'from tlz import curry' fails: ImportError: tlz.curry

### ISSUE THREAD

**Issue by yurivict** [pytoolz/toolz#573] opened 2024-01-11 18:26 UTC
```
$ python3.9
Python 3.9.18 (main, Dec 10 2023, 01:22:40) 
[Clang 16.0.6 (https://github.com/llvm/llvm-project.git llvmorg-16.0.6-0-g7cbf1 on freebsd14
Type "help", "copyright", "credits" or "license" for more information.
>>> from tlz import curry
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/tlz/_build_tlz.py", line 55, in exec_module
    toolz_mods = self._load_toolz(module.__name__)
  File "/usr/local/lib/python3.9/site-packages/tlz/_build_tlz.py", line 29, in _load_toolz
    raise ImportError(fullname)
ImportError: tlz.curry
>>>
```

One test, toolz/tests/test_tlz.py::test_tlz, fails with the same error:
```
_________________________________________________________________________________________ test_tlz __________________________________________________________________________________________

    def test_tlz():
        import tlz
>       tlz.curry
E       AttributeError: module 'tlz' has no attribute 'curry'

toolz/tests/test_tlz.py:6: AttributeError
=============================================================================== 1 failed, 179 passed in 2.59s ===============================================================================
```

```import_module('toolz.curry')``` fails with: ```No module named 'toolz.curry'```.

```from toolz import curry``` succeeds.

Version: 0.12.0
Python-3.9
FreeBSD 14.0

**Comment by yurivict** [comment] 2024-01-24 06:32
0.12.1 has 2 failures:

```
========================================================================================= FAILURES ==========================================================================================
______________________________________________________________________________ test_introspect_builtin_modules ______________________________________________________________________________

    def test_introspect_builtin_modules():
        mods = [builtins, functools, itertools, operator, toolz,
                toolz.functoolz, toolz.itertoolz, toolz.dicttoolz, toolz.recipes]
    
        denylist = set()
    
        def add_denylist(mod, attr):
            if hasattr(mod, attr):
                denylist.add(getattr(mod, attr))
    
        add_denylist(builtins, 'basestring')
        add_denylist(builtins, 'NoneType')
        add_denylist(builtins, '__metaclass__')
        add_denylist(builtins, 'sequenceiterator')
    
        def is_missing(modname, name, func):
            if name.startswith('_') and not name.startswith('__'):
                return False
            if name.startswith('__pyx_unpickle_') or name.endswith('_cython__'):
                return False
            try:
                if issubclass(func, BaseException):
                    return False
            except TypeError:
                pass
            try:
                return (callable(func)
                        and func.__module__ is not None
                        and modname in func.__module__
                        and is_partial_args(func, (), {}) is not True
                        and func not in denylist)
            except AttributeError:
                return False
    
        missing = {}
        for mod in mods:
            modname = mod.__name__
            for name, func in vars(mod).items():
                if is_missing(modname, name, func):
                    if modname not in missing:
                        missing[modname] = []
                    missing[modname].append(name)
        if missing:
            messages = []
            for modname, names in sorted(missing.items()):
                msg = '{}:\n    {}'.format(modname, '\n    '.join(sorted(names)))
                messages.append(msg)
            message = 'Missing introspection for the following callables:\n\n'
>           raise AssertionError(message + '\n\n'.join(messages))
E           AssertionError: Missing introspection for the following callables:
E           
E           builtins:
E               __orig_import__

toolz/tests/test_inspect_args.py:433: AssertionError
_________________________________________________________________________________________ test_tlz __________________________________________________________________________________________

    def test_tlz():
        import tlz
>       tlz.curry
E       AttributeError: module 'tlz' has no attribute 'curry'

toolz/tests/test_tlz.py:6: AttributeError
=============================================================================== 2 failed, 178 passed in 2.23s ===============================================================================
*** Error code 1
```

**Comment by thisisamardeep** [comment] 2024-02-18 09:49
I could not reproduce this issue on  0.12.0 on 3.9. Just to be clear you mean the tag 0.12.0 correct ?

**Comment by yurivict** [comment] 2024-02-18 10:13
> Just to be clear you mean the tag 0.12.0 correct ?

Yes.

**Comment by thisisamardeep** [comment] 2024-02-18 12:34
Are you able to reproduce it ?

**Comment by jrbourbeau** [comment] 2024-09-27 20:39
Closing as I'm not able to reproduce with Python 3.9 and toolz 0.12.0 either

```
(test) ➜  ~ python
Python 3.9.20 | packaged by conda-forge | (main, Sep 22 2024, 14:06:09)
[Clang 17.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tlz
>>> tlz.__version__
'0.12.0'
>>> tlz.curry
<class 'toolz.functoolz.curry'>
```

@yurivict feel free to re-open if this is still a problem for you

**Closed by jrbourbeau** 2024-09-27 20:39 UTC
